plugins {
    alias libs.plugins.android.application
    alias libs.plugins.jetbrains.kotlin.plugin.serialization
    alias libs.plugins.jetbrains.kotlin.plugin.compose
    alias libs.plugins.hilt
    alias libs.plugins.ksp
    alias libs.plugins.google.services
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    compileSdk 37
    defaultConfig {
        applicationId "com.jeeps.gamecollector"
        minSdkVersion 26
        targetSdkVersion 35
        versionCode 40
        versionName "6.3.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        buildConfigField "String", "IGDB_CLIENT_ID", "\"${localProperties.getProperty('IGDB_CLIENT_ID')}\""
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        compose true
        buildConfig true
    }

    // TODO: Figure out why this is happening after upgrading to kotlin 2
    lint {
        disable "NullSafeMutableLiveData"
    }

    namespace 'com.jeeps.gamecollector'
}

dependencies {
    def composeBom = libs.compose.bom
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation composeBom
    androidTestImplementation composeBom

    /* Core libraries */
    implementation libs.core.ktx
    implementation libs.appcompat
    implementation libs.legacy.support.v4
    implementation libs.navigation.ui
    implementation libs.navigation.fragment
    implementation libs.palette
    implementation libs.kotlinx.coroutines.android
    implementation libs.kotlinx.coroutines.core
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.hilt.android
    ksp libs.hilt.compiler

    implementation libs.kotlinx.serialization.json
    implementation libs.activity

    /* Compose */
    implementation libs.compose.material3
    implementation libs.compose.ui
    debugImplementation libs.compose.ui.tooling
    implementation libs.compose.ui.tooling.preview
    implementation libs.activity.compose
    implementation libs.lifecycle.viewmodel.compose
    implementation libs.compose.runtime
    implementation libs.constraintlayout.compose
    implementation libs.material.icons.extended
    implementation libs.navigation.compose
    implementation libs.hilt.navigation.compose
    implementation libs.hilt.lifecycle.viewmodel.compose

    /* UI */
    implementation libs.constraintlayout
    implementation libs.material
    implementation libs.flexbox
    implementation libs.cardview
    implementation libs.recyclerview

    /* Firebase */
    implementation libs.firebase.analytics
    implementation libs.firebase.ui.auth
    implementation libs.firebase.auth
    implementation libs.firebase.database
    implementation libs.firebase.storage
    implementation libs.firebase.firestore

    /* Third party */
    implementation libs.shapeofview

    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.converter.scalars

    implementation libs.picasso
    implementation libs.okhttp
    implementation libs.logging.interceptor

    implementation libs.json
    implementation libs.compressor
    implementation libs.williamchart
    implementation libs.sparkbutton
    implementation libs.networkresponseadapter

    implementation libs.lottie.compose

    implementation libs.coil
    implementation libs.coil.compose

    implementation libs.toolbar.compose

    /* Tests */
    testImplementation libs.junit
    androidTestImplementation libs.runner
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.compose.ui.test.junit4
    debugImplementation libs.compose.ui.test.manifest
}

configurations {
    configureEach {
        exclude group: 'org.json', module: 'json'
    }
}
