name: Android CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Get IGB Api Key
      env:
        IGDB_CLIENT_ID: ${{ secrets.IGDB_CLIENT_ID }}
      run: echo IGDB_CLIENT_ID="$IGDB_CLIENT_ID" > ./local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
